#!/usr/bin/env python
# vim: set ft=python:

import argparse, random, os, math, shutil, sys
from os import getcwd, listdir
from os.path import isfile, isdir, join

parser = argparse.ArgumentParser(description='Randomly moves files to a directory')

parser.add_argument("source", nargs='?')
parser.add_argument("dest")
parser.add_argument("-p", "--percent", default=50,
        help="The percent of the directory to move, default is 50", type=int)

args = parser.parse_args()

if not args.source:
    args.source = os.getcwd()

if not isdir(args.dest):
    sys.exit("rmv: error: {} is not a directory".format(args.dest))

if not isdir(args.source):
    sys.exit("rmv: error: {} is not a directory".format(args.dest))

if args.percent > 100 or args.percent < 0:
    sys.exit("rmv: error: Invalid percentage")

files = [f for f in os.listdir(args.source) if f[0] != '.' and isfile(join(getcwd(),f))]

percent = int(math.ceil(args.percent/100.0*len(files)))

for f in random.sample(files, percent):
    shutil.move(f, args.dest)
